### ISSUE TITLE
error occured

### ISSUE THREAD

**Issue by weissxu** [Erudika/para-cli#22]
# para-cli setup
Para Access Key: app:para
Para Secret Key: b8db69a24a43f2ce134909f164a45263
Para Endpoint: http://localhost:8080
✔ New JWT generated and saved in /root/.config/para-cli-nodejs/config.json
readline.js:1280
            throw err;
            ^

TypeError: config.get is not a function
    at listApps (file:///usr/local/lib/nodejs/node-v14.18.1-linux-x64/lib/node_modules/para-cli/index.js:430:75)
    at file:///usr/local/lib/nodejs/node-v14.18.1-linux-x64/lib/node_modules/para-cli/index.js:66:6
    at Interface._onLine (readline.js:432:5)
    at Interface._line (readline.js:791:8)
    at Interface._ttyWrite (readline.js:1136:14)
    at ReadStream.onkeypress (readline.js:265:10)
    at ReadStream.emit (events.js:400:28)
    at emitKeys (internal/readline/utils.js:358:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1270:36)

**Comment by weissxu** [comment]
So，how to fix it? @albogdano
